In [1]:
import re
import math
import keras
import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds

2025-08-19 14:30:19.391049: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-08-19 14:30:19.408236: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-08-19 14:30:19.413704: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-08-19 14:30:19.427689: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
gpus = tf.config.experimental.list_physical_devices('GPU')

for gpu in gpus:
    details = tf.config.experimental.get_device_details(gpu)
    compute_capability = details.get('compute_capability', 'Unknown')
    print(f"Device: {gpu.name}, Compute Capability: {compute_capability}")
    
    try:
        tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        print(e)

Device: /physical_device:GPU:0, Compute Capability: (7, 5)


I0000 00:00:1755613821.807288   58416 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1755613821.863094   58416 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1755613821.863487   58416 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1755613821.864756   58416 cuda_executor.cc:1015] successful NUMA node read from SysFS ha

In [3]:
MODEL_PATH = "../model/"

In [4]:
def print_mnist(ds):
    import matplotlib.pyplot as plt

    # Function to display MNIST images
    def show_images(images, labels):
        plt.figure(figsize=(10, 5))
        for i in range(10):
            plt.subplot(2, 5, i + 1)
            plt.imshow(images[i].numpy(), cmap='gray')
            plt.title(f"Label: {labels[i].numpy()}")
            plt.axis("off")
        plt.show()

    # Display a few images from the training set
    num_images_to_display = 10
    train_images, train_labels = next(iter(ds.batch(num_images_to_display)))
    show_images(train_images, train_labels)


In [5]:
(_ds_train, _ds_test), _ds_info = tfds.load(
    'mnist',
    split=['train', 'test'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True,
)

I0000 00:00:1755613821.939956   58416 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1755613821.940285   58416 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1755613821.940554   58416 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1755613822.054770   58416 cuda_executor.cc:1015] successful NUMA node read from SysFS ha

In [6]:
def normalize_img(image, label):
  """Normalizes images: `uint8` -> `float32`."""
  return tf.cast(image, tf.float32) / 255., label

In [7]:
ds_train = _ds_train.map(
    normalize_img, num_parallel_calls=tf.data.AUTOTUNE
)
ds_train = ds_train.cache()
ds_train = ds_train.shuffle(_ds_info.splits['train'].num_examples)
ds_train = ds_train.batch(128)
ds_train = ds_train.prefetch(tf.data.AUTOTUNE)

In [8]:
ds_test = _ds_test.map(
    normalize_img, num_parallel_calls=tf.data.AUTOTUNE
)
ds_test = ds_test.batch(128)
ds_test = ds_test.cache()
ds_test = ds_test.prefetch(tf.data.AUTOTUNE)

In [9]:
model = keras.models.load_model(f'{MODEL_PATH}model.keras')
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 12, 12, 5)      │           130 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 12, 12, 5)      │            20 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 12, 12, 5)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d               │ (None, 6, 6, 5)        │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 180)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 10)             │         1,810 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,862 (22.90 KB)

 Trainable params: 1,950 (7.62 KB)

 Non-trainable params: 10 (40.00 B)

 Optimizer params: 3,902 (15.25 KB)

In [10]:
for t_v in model.variables: # changed from trainable_variables
    print("name of weight: ", t_v.name)
    print("shape of the weight", t_v.shape)
    print("value type: ", t_v.numpy().dtype)
    print()

name of weight:  kernel
shape of the weight (5, 5, 1, 5)
value type:  float32

name of weight:  bias
shape of the weight (5,)
value type:  float32

name of weight:  gamma
shape of the weight (5,)
value type:  float32

name of weight:  beta
shape of the weight (5,)
value type:  float32

name of weight:  moving_mean
shape of the weight (5,)
value type:  float32

name of weight:  moving_variance
shape of the weight (5,)
value type:  float32

name of weight:  kernel
shape of the weight (180, 10)
value type:  float32

name of weight:  bias
shape of the weight (10,)
value type:  float32



In [11]:
model.trainable_variables[2].path

'batch_normalization/gamma'

In [12]:
for t_v in model.variables:
    _name = t_v.path
    
    if "_" not in _name.split("/")[0] or _name.split("/")[0] == "batch_normalization":
        name = _name.split("/")[0] + "_0/" + _name.split("/")[1]
    # else:
    #     name = "/".join(name.split("/")[1:])
    
    name = name.replace("/", "_")
    
    if _name.split("/")[1] == "moving_variance":
        target_path = t_v.path
        for layer in model.layers:
            for var in layer.variables:
                if var.path == target_path:
                    print("BN epsilon:", layer.epsilon)
                    
                    moving_variance = layer.moving_variance.numpy()
                    epsilon = layer.epsilon

                    bn_denominator = np.sqrt(moving_variance + epsilon)
                    print(bn_denominator)
                    bn_denominator = 1/bn_denominator
                    print(bn_denominator)
                    np.save(f'{MODEL_PATH}{name}', bn_denominator.flatten())
                    print(f'{_name.split("/")[1]} type: {bn_denominator.dtype}')
                    break
    elif _name.split("/")[1] == "moving_mean":
        moving_mean = t_v.numpy()
        print(moving_mean)
        moving_mean = -moving_mean
        print(moving_mean)
        np.save(f'{MODEL_PATH}{name}', moving_mean.flatten())
        print(f'{_name.split("/")[1]} type: {moving_mean.dtype}')
    else:
        np.save(f'{MODEL_PATH}{name}', t_v.numpy().flatten())
        print(f'{_name.split("/")[1]} type: {t_v.numpy().dtype}')

kernel type: float32
bias type: float32
gamma type: float32
beta type: float32
[-0.05307069 -0.3848538  -0.00624614 -0.04942603 -0.26618075]
[0.05307069 0.3848538  0.00624614 0.04942603 0.26618075]
moving_mean type: float32
BN epsilon: 0.001
[0.3500521  0.63501    0.38577408 0.45407248 0.515422  ]
[2.8567178 1.5747783 2.5921907 2.2022915 1.9401578]
moving_variance type: float32
kernel type: float32
bias type: float32


In [13]:
x_ls = []
y_ls = []
for x, y in iter(ds_test.unbatch()):
    x_ls.append(x)
    y_ls.append(y)

x_np = np.array(x_ls)
y_np = np.array(y_ls)

select_el = 500
print(x_np[select_el].shape, y_ls[select_el])

np.save(f"{MODEL_PATH}test_x", x_np.flatten()) # .map(lambda x: tf.cast(x, tf.float32))
np.save(f"{MODEL_PATH}test_y", y_np.flatten())

print(x_np.dtype)
print(y_np.dtype)

2025-08-19 14:30:25.771831: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


(28, 28, 1) tf.Tensor(2, shape=(), dtype=int64)
float32
int64


In [14]:
poly_str = "+1.0588376954228294*x**0+0.4917208555350564*x**1+0.04654061020028913*x**2+0.00026703833952889034*x**3-7.414076828643847e-05*x**4-1.1386535999933917e-06*x**5"
domain = None
level = 0

terms = re.findall(r'[+-]?\d*\.?\d+(?:e[+-]?\d+)?', poly_str)
consts = [float(term) for term in terms]
poly_consts = np.array([v for i, v in enumerate(consts) if i % 2 != 1]) #, dtype=np.float32)

np.save(f"{MODEL_PATH}poly_consts_{level}", poly_consts.flatten())

if domain:
    poly_domain = np.array([1/domain, domain])
    np.save(f"{MODEL_PATH}poly_domain_{level}", poly_domain.flatten())

In [15]:
poly_consts

array([ 1.05883770e+00,  4.91720856e-01,  4.65406102e-02,  2.67038340e-04,
       -7.41407683e-05, -1.13865360e-06])

In [16]:
poly_consts.dtype

dtype('float64')

In [17]:
if domain:
    poly_domain

In [18]:
if domain:
    poly_domain.dtype